/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { InfoContract__factory } from "./InfoContract__factory";
export { MetaCoin__factory } from "./MetaCoin__factory";
