/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InfoContract } from "./InfoContract";
export type { MetaCoin } from "./MetaCoin";
export * as factories from "./factories";
export { InfoContract__factory } from "./factories/InfoContract__factory";
export { MetaCoin__factory } from "./factories/MetaCoin__factory";
